### ISSUE TITLE
Добавить лицензию

### ISSUE THREAD

**Issue by EvilBeaver** [YPermitin/V8Formats#1]
Проекту требуется лицензия. Кроме того, кажется, что правильно будет упомянуть не только на Инфостарте, но и на самом гитхабе откуда идут истоки - v8unpack.

Он есть на github и есть более быстрый его форк от @dmpas. Кажется, что ссылки на эти репо (а не только на инфостарт) тоже нужны в README.

**Comment by YPermitin** [comment]
Ок, в скором времени добавлю лицензию и ссылки.

**Comment by YPermitin** [comment]
Используется лицензия MIT. Текст лицензии на рус. и англ. языке добавлен.
